blank_issues_enabled: false
contact_links:
  - name: 💬 技術的な質問
    url: https://slack.com
    about: 技術的な質問はSlackで聞いてください
  - name: 📚 学習メモの共有
    url: https://slack.com
    about: 学んだことや気づきをSlackで共有しましょう
